services:
  just-web-agent:
    container_name: just-web-agent
    image: ghcr.io/longevity-genie/just-agents:main-gpu
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      APP_PORT: "8088" #app port inside container
      #APP_HOST: "0.0.0.0" #app host inside container, 0's to expose
      AGENT_PORT: "8088" #agent port for chat to access
      AGENT_HOST: "http://just-web-agent" #agent host for chat to access
      #AGENT_WORKERS: "4"
      AGENT_TITLE: "Just Chat REST API node"
      AGENT_PARENT_SECTION: ""
      AGENT_DEBUG: "true"
      AGENT_REMOVE_SYSTEM_PROMPT: "false"
      AGENT_CONFIG: "/app/agent_profiles.yaml"
    ports:
      - "127.0.0.1:9090:8089"
    volumes:
      - "./data:/data"
      - "./env:/app/env"
      - "./models.d:/app/models.d"
      - "./tools:/app/tools"
      - "./agent_profiles.yaml:/app/agent_profiles.yaml"
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    restart: "always"
    depends_on:
      key-env-generator:
        condition: service_completed_successfully

  chat-env-generator:
    image: python:3.10-slim
    user: "${UID:-1000}:${GID:-1000}"
    container_name: chat-env-generator
    volumes:
      - "./scripts:/scripts"
      - "./models.d:/models.d"
      - "./env:/env"
    working_dir: /scripts
    entrypoint: ["/bin/sh", "-c", "sleep 15 && python3 prepare_env_local.py"]
    depends_on:
      just-web-agent:
        condition: service_started
    restart: "no"

  key-env-generator:
    image: python:3.10-slim
    user: "${UID:-1000}:${GID:-1000}"
    container_name: key-env-generator
    volumes:
      - "./scripts:/scripts"
      - "./env:/env"
    working_dir: /scripts
    entrypoint: [ "/bin/sh", "-c", "python3 prepare_keys.py" ]

  huggingchat-ui:
    container_name: just-chat-ui
    image: ghcr.io/longevity-genie/chat-ui/chat-ui:sha-325df57
    environment:
      ALLOW_INSECURE_COOKIES: "true"
      INCLUDE_DB: "False"
    volumes:
      - "./env/.env.local:/app/.env.local"
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      chat-env-generator:
        condition: service_completed_successfully
      chat-mongo:
        condition: service_started
    restart: "no"

  chat-mongo:
    container_name: just-chat-mongodb
    image: mongo:latest
    restart: always
    env_file:
      - ./env/.env.mongo
    ports:
      - "27017"
    volumes:
      - "./volumes/mongo/db:/data/db"

  meilisearch: #container required for searching the papers
    container_name: meilisearch
    image: getmeili/meilisearch:v1.13.0-rc.1 # we have to use it because migration got easier
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=fancy_master_key
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
      - MEILI_EXPERIMENTAL_ENABLE_METRICS=true
      - MEILI_EXPERIMENTAL_ENABLE_VECTORS=true
    ports:
      - ${MEILI_PORT:-7700}:7700
    volumes:
      - ./data.ms:/data.ms
    restart: unless-stopped

networks:
  default:
    name: chat-server
